sudo: false
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - nightly
env:
    - FRAMEWORK=django~=1.6.0
    - FRAMEWORK=django~=1.7.0
    - FRAMEWORK=django~=1.8.0
    - FRAMEWORK=django~=1.9.0
    - FRAMEWORK=django~=1.10.0
    - FRAMEWORK=django~=1.11.0
    - FRAMEWORK=flask~=0.10.0
    - FRAMEWORK=flask~=0.11.0
    - FRAMEWORK=flask~=0.12.0
matrix:
    allow_failures:
        - python: nightly
    exclude:
        - python: 3.3
          env: FRAMEWORK=django~=1.9.0
        - python: 3.3
          env: FRAMEWORK=django~=1.10.0
        - python: 3.3
          env: FRAMEWORK=django~=1.11.0
        - python: 3.4
          env: FRAMEWORK=django~=1.6.0
        - python: 3.5
          env: FRAMEWORK=django~=1.6.0
        - python: 3.5
          env: FRAMEWORK=django~=1.7.0
        - python: 3.6
          env: FRAMEWORK=django~=1.6.0
        - python: 3.6
          env: FRAMEWORK=django~=1.7.0
        - python: nightly
          env: FRAMEWORK=django~=1.6.0
        - python: nightly
          env: FRAMEWORK=django~=1.7.0
    fast_finish: true
branches:
    except:
        - mrosemartin84
        - soapbox
install:
    - pip install -q "${FRAMEWORK}"
    - pip install -q -r dev_requirements.txt
    - pip install -q -e .
script:
    - nosetests --nocapture
